### ISSUE TITLE
warning request: cast between calling conventions

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/clang#130]
This should produce a warning (really an error in pure capability mode):
```C
typedef        bool_t (*xdrproc_t)(XDR *, ...);

bool_t a_proc(XDR *, void *);

xdrproc_t
foo()
{
    return (xdrproc_t)a_proc;
}
```
The reverse should also produce an error, but I've not seen any of those so it's less urgent.

**Comment by arichardson** [comment]
This was fixed in https://github.com/CTSRD-CHERI/clang/commit/d9f11218a4d7ad9a883de858423a178431301d6c and the follow-up commits to reduce false-positives with the warning (https://github.com/CTSRD-CHERI/clang/commit/3bd203b825ba63191a063f2e3568ad7cdf238b1e and https://github.com/CTSRD-CHERI/clang/commit/1818be2868777fe87f3282a6f634ac1b9fda6ff3). The new warning is an error by default and also includes the cast from variadic to non-variadic.
