### ISSUE TITLE
switch((intptr_t)foo) never makes sense in pure-cabability ABI and should be a warning

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/clang#132]
The FreeBSD local code contained this gem:
```C
static inline locale_t get_real_locale(locale_t locale)
 {
       switch ((intptr_t)locale) {
                case 0: return (&__xlocale_C_locale);
                case -1: return (&__xlocale_global_locale);
                default: return (locale);
}
```
If you aren't paying attention it looks fine, but the switch becomes `switch (cheri_getoffset(locale))` and valid `locale` variables with bounds have offsets of `0`.

**Comment by davidchisnall** [comment]
Unfortunately, it does make sense in some contexts.  It's only the existence of the third case that makes this nonsense.  If you have a pointer type that solely contains integer values, then this construct does make sense.

**Comment by brooksdavis** [comment]
If your pointer type contains solely integer values, you can change this to `switch ((vaddr_t)locale)` and the result won't change where as with `switch ((intptr_t)locale)` it's almost certainly wrong if real pointers are involved.

**Comment by brooksdavis** [comment]
At a minimum, ever switch statement like this needs to be carefully audited so requiring an explicit cast to a normal integer type either in place of `intptr_t` or in after `intptr_t` seems like the right thing to do.

**Comment by RichardsonAlex** [comment]
I also think it makes sense to make it equivalent to `switch ((vaddr_t)locale)`. Having a switch on uintptr_t mean `switch (cheri_getoffset(value))` is extremely surprising and for the few cases where this is actually the intended use case we could just use `switch (cheri_getoffset(value))`?
While fixing the warning caused by #126 I saw lots of caes in e.g. getgrent.c/getpwent.c where a void* argument is cast to a enum type and used in a switch statement. A simple solution to the warnings would be to just use uintptr_t instead of void* but  because it is used in switch statements I feel like this might cause issues. I might be possible to get to the switch statement with a valid capability where the offset happens to be one of the enum constants...

Also for a pointer type that solely contains integer values, shouldn't a cast to `vaddr_t` be the same as `cheri_getoffset()`?
